/** US English IPA pronunciations keyed by term */
export const IPA_BY_TERM: Record<string, string> = {
  hello: "həˈloʊ",
  goodbye: "ɡʊdˈbaɪ",
  please: "pliz",
  "thank you": "θæŋk ju",
  sorry: "ˈsɑri",
  yes: "jɛs",
  no: "noʊ",
  welcome: "ˈwɛlkəm",
  family: "ˈfæməli",
  friend: "frɛnd",
  mother: "ˈmʌðər",
  father: "ˈfɑðər",
  child: "tʃaɪld",
  baby: "ˈbeɪbi",
  man: "mæn",
  woman: "ˈwʊmən",
  people: "ˈpipəl",
  name: "neɪm",
  house: "haʊs",
  home: "hoʊm",
  room: "rum",
  door: "dɔr",
  window: "ˈwɪndoʊ",
  school: "skul",
  hospital: "ˈhɑspɪtəl",
  shop: "ʃɑp",
  city: "ˈsɪti",
  country: "ˈkʌntri",
  water: "ˈwɔtər",
  food: "fud",
  bread: "brɛd",
  rice: "raɪs",
  milk: "mɪlk",
  coffee: "ˈkɔfi",
  tea: "ti",
  fruit: "frut",
  apple: "ˈæpəl",
  meat: "mit",
  time: "taɪm",
  day: "deɪ",
  night: "naɪt",
  morning: "ˈmɔrnɪŋ",
  week: "wik",
  month: "mʌnθ",
  year: "jɪr",
  today: "təˈdeɪ",
  tomorrow: "təˈmɑroʊ",
  yesterday: "ˈjɛstərdeɪ",
  happy: "ˈhæpi",
  sad: "sæd",
  big: "bɪɡ",
  small: "smɔl",
  fast: "fæst",
  slow: "sloʊ",
  hot: "hɑt",
  cold: "koʊld",
  new: "nu",
  old: "oʊld",
  good: "ɡʊd",
  bad: "bæd",
  beautiful: "ˈbjutəfəl",
  easy: "ˈizi",
  hard: "hɑrd",
  learn: "lɜrn",
  speak: "spik",
  listen: "ˈlɪsən",
  read: "rid",
  write: "raɪt",
  eat: "it",
  drink: "drɪŋk",
  sleep: "slip",
  walk: "wɔk",
  run: "rʌn",
  work: "wɜrk",
  play: "pleɪ",
  help: "hɛlp",
  buy: "baɪ",
  give: "ɡɪv",
  book: "bʊk",
  phone: "foʊn",
  car: "kɑr",
  money: "ˈmʌni",
  sun: "sʌn",
  rain: "reɪn",
  tree: "tri",
  flower: "ˈflaʊər",
  dog: "dɔɡ",
  cat: "kæt",
  bird: "bɜrd",
  color: "ˈkʌlər",
  red: "rɛd",
  blue: "blu",
  green: "ɡrin",
  travel: "ˈtrævəl",
  experience: "ɪkˈspɪriəns",
  achieve: "əˈtʃiv",
  improve: "ɪmˈpruv",
  challenge: "ˈtʃælɪndʒ",
  opportunity: "ˌɑpərˈtunəti",
  decision: "dɪˈsɪʒən",
  career: "kəˈrɪr",
  interview: "ˈɪntərˌvju",
  salary: "ˈsæləri",
  colleague: "ˈkɑliɡ",
  deadline: "ˈdɛdˌlaɪn",
  research: "rɪˈsɜrtʃ",
  graduate: "ˈɡrædʒuˌeɪt",
  assignment: "əˈsaɪnmənt",
  communicate: "kəˈmjunəˌkeɪt",
  confident: "ˈkɑnfɪdənt",
  creative: "kriˈeɪtɪv",
  efficient: "ɪˈfɪʃənt",
  generous: "ˈdʒɛnərəs",
  patient: "ˈpeɪʃənt",
  reliable: "rɪˈlaɪəbəl",
  responsible: "rɪˈspɑnsəbəl",
  curious: "ˈkjʊriəs",
  grateful: "ˈɡreɪtfəl",
  persuade: "pərˈsweɪd",
  negotiate: "nɪˈɡoʊʃiˌeɪt",
  apologize: "əˈpɑləˌdʒaɪz",
  encourage: "ɪnˈkɜrɪdʒ",
  influence: "ˈɪnfluəns",
  environment: "ɪnˈvaɪrənmənt",
  community: "kəˈmjunəti",
  culture: "ˈkʌltʃər",
  pollution: "pəˈluʃən",
  recycle: "riˈsaɪkəl",
  volunteer: "ˌvɑlənˈtɪr",
  tradition: "trəˈdɪʃən",
  democracy: "dɪˈmɑkrəsi",
  economy: "ɪˈkɑnəmi",
  technology: "tɛkˈnɑlədʒi",
  analyze: "ˈænəˌlaɪz",
  conclude: "kənˈklud",
  evidence: "ˈɛvɪdəns",
  theory: "ˈθɪri",
  significant: "sɪɡˈnɪfɪkənt",
  approximately: "əˈprɑksɪmətli",
  consequence: "ˈkɑnsəkwəns",
  priority: "praɪˈɔrəti",
  strategy: "ˈstrætədʒi",
  innovation: "ˌɪnəˈveɪʃən",
};

export function getIpaForTerm(term: string): string | null {
  return IPA_BY_TERM[term.toLowerCase()] ?? null;
}
