/** Kid-friendly photo URLs (Wikimedia Commons, free to use) */
export const IMAGE_BY_TERM: Record<string, string> = {
  hello: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Wave_hand_greeting.jpg/320px-Wave_hand_greeting.jpg",
  goodbye: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Waving_hand_icon.svg/320px-Waving_hand_icon.svg.png",
  family: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Multi-Generational_Family_Outside_House.jpg/320px-Multi-Generational_Family_Outside_House.jpg",
  mother: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Mother_and_child_in_Afghanistan.jpg/320px-Mother_and_child_in_Afghanistan.jpg",
  father: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Father_and_son.jpg/320px-Father_and_son.jpg",
  child: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Happy_child.jpg/320px-Happy_child.jpg",
  baby: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Portrait_of_a_newborn_baby.jpg/320px-Portrait_of_a_newborn_baby.jpg",
  house: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/House_LCCN2013648789.jpg/320px-House_LCCN2013648789.jpg",
  home: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Home_icon.svg/320px-Home_icon.svg.png",
  school: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/First_school.jpg/320px-First_school.jpg",
  hospital: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Hospital.svg/320px-Hospital.svg.png",
  shop: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Grocery_store.jpg/320px-Grocery_store.jpg",
  city: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/New_york_times_square-terabass.jpg/320px-New_york_times_square-terabass.jpg",
  country: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Countryside_in_England.jpg/320px-Countryside_in_England.jpg",
  water: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Water_drop_001.jpg/320px-Water_drop_001.jpg",
  food: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
  bread: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Fresh_made_bread_05.jpg/320px-Fresh_made_bread_05.jpg",
  rice: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Cooked_rice.jpg/320px-Cooked_rice.jpg",
  milk: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Glass_of_milk.jpg/320px-Glass_of_milk.jpg",
  coffee: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/A_small_cup_of_coffee.JPG/320px-A_small_cup_of_coffee.JPG",
  tea: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Tea_in_cup.jpg/320px-Tea_in_cup.jpg",
  fruit: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Collage_of_Nine_Fruits.jpg/320px-Collage_of_Nine_Fruits.jpg",
  apple: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Red_Apple.jpg/320px-Red_Apple.jpg",
  meat: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Steak.jpg/320px-Steak.jpg",
  sun: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819.jpg/320px-The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819.jpg",
  rain: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Rain_drops_on_a_window.jpg/320px-Rain_drops_on_a_window.jpg",
  tree: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Ash_Tree_-_geograph.org.uk_-_590710.jpg/320px-Ash_Tree_-_geograph.org.uk_-_590710.jpg",
  flower: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Sunflower_sky_backdrop.jpg/320px-Sunflower_sky_backdrop.jpg",
  dog: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/YellowLabradorLooking_new.jpg/320px-YellowLabradorLooking_new.jpg",
  cat: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/320px-Cat03.jpg",
  bird: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Common_Kingfisher_Alcedo_atthis.jpg/320px-Common_Kingfisher_Alcedo_atthis.jpg",
  book: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Gutenberg_Bible%2C_Lenox_Copy%2C_New_York_Public_Library%2C_2009._Pic_01.jpg/320px-Gutenberg_Bible%2C_Lenox_Copy%2C_New_York_Public_Library%2C_2009._Pic_01.jpg",
  phone: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Mobile_phone_evolution.jpg/320px-Mobile_phone_evolution.jpg",
  car: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Toyota_car.jpg/320px-Toyota_car.jpg",
  money: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/US_dollar_coins.jpg/320px-US_dollar_coins.jpg",
  environment: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Earth_day.jpg/320px-Earth_day.jpg",
  travel: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Gull_portrait_ca_usa.jpg/320px-Gull_portrait_ca_usa.jpg",
};

/** Emoji fallback — every word gets a visual for kids */
export const EMOJI_BY_TERM: Record<string, string> = {
  hello: "👋",
  goodbye: "👋",
  please: "🙏",
  "thank you": "🙏",
  sorry: "😔",
  yes: "✅",
  no: "❌",
  welcome: "🤗",
  family: "👨‍👩‍👧‍👦",
  friend: "🤝",
  mother: "👩",
  father: "👨",
  child: "🧒",
  baby: "👶",
  man: "👨",
  woman: "👩",
  people: "👥",
  name: "🏷️",
  house: "🏠",
  home: "🏡",
  room: "🚪",
  door: "🚪",
  window: "🪟",
  school: "🏫",
  hospital: "🏥",
  shop: "🏪",
  city: "🏙️",
  country: "🌍",
  water: "💧",
  food: "🍽️",
  bread: "🍞",
  rice: "🍚",
  milk: "🥛",
  coffee: "☕",
  tea: "🍵",
  fruit: "🍎",
  apple: "🍎",
  meat: "🥩",
  time: "⏰",
  day: "☀️",
  night: "🌙",
  morning: "🌅",
  week: "📅",
  month: "📆",
  year: "🗓️",
  today: "📍",
  tomorrow: "➡️",
  yesterday: "⬅️",
  happy: "😊",
  sad: "😢",
  big: "🐘",
  small: "🐜",
  fast: "⚡",
  slow: "🐢",
  hot: "🔥",
  cold: "❄️",
  new: "✨",
  old: "📜",
  good: "👍",
  bad: "👎",
  beautiful: "🌸",
  easy: "😌",
  hard: "💪",
  learn: "📚",
  speak: "🗣️",
  listen: "👂",
  read: "📖",
  write: "✍️",
  eat: "😋",
  drink: "🥤",
  sleep: "😴",
  walk: "🚶",
  run: "🏃",
  work: "💼",
  play: "🎮",
  help: "🆘",
  buy: "🛒",
  give: "🎁",
  book: "📕",
  phone: "📱",
  car: "🚗",
  money: "💰",
  sun: "☀️",
  rain: "🌧️",
  tree: "🌳",
  flower: "🌺",
  dog: "🐕",
  cat: "🐈",
  bird: "🐦",
  color: "🎨",
  red: "🔴",
  blue: "🔵",
  green: "🟢",
  travel: "✈️",
  experience: "🌟",
  achieve: "🏆",
  improve: "📈",
  challenge: "🧗",
  opportunity: "🚪",
  decision: "🤔",
  career: "👔",
  interview: "🎤",
  salary: "💵",
  colleague: "👥",
  deadline: "⏳",
  research: "🔬",
  graduate: "🎓",
  assignment: "📝",
  communicate: "💬",
  confident: "😎",
  creative: "🎨",
  efficient: "⚙️",
  generous: "💝",
  patient: "🧘",
  reliable: "🔒",
  responsible: "✅",
  curious: "🔍",
  grateful: "💖",
  persuade: "🗣️",
  negotiate: "🤝",
  apologize: "🙇",
  encourage: "💪",
  influence: "📣",
  environment: "🌿",
  community: "🏘️",
  culture: "🎭",
  pollution: "🏭",
  recycle: "♻️",
  volunteer: "🤲",
  tradition: "🎎",
  democracy: "🗳️",
  economy: "📊",
  technology: "💻",
  analyze: "🔎",
  conclude: "✔️",
  evidence: "📋",
  theory: "💡",
  significant: "❗",
  approximately: "≈",
  consequence: "➡️",
  priority: "⭐",
  strategy: "🗺️",
  innovation: "🚀",
};

export function getWordEmoji(term: string): string {
  return EMOJI_BY_TERM[term.toLowerCase()] ?? "📖";
}

export function getWordImageUrl(term: string, storedUrl?: string | null): string | null {
  if (storedUrl?.trim()) return storedUrl.trim();
  return IMAGE_BY_TERM[term.toLowerCase()] ?? null;
}

export function getDefaultWordImageUrl(term: string): string | null {
  return IMAGE_BY_TERM[term.toLowerCase()] ?? null;
}
